name: PSP_scipy
dependencies:
- hdf5=1.8.15.1=2
- mkl=11.3.1=0
- numexpr=2.4.6=np110py27_1
- numpy=1.10.4=py27_0
- openssl=1.0.2g=0
- pandas=0.17.1=np110py27_0
- pip=8.0.3=py27_0
- pytables=3.2.2=np110py27_0
- python=2.7.11=0
- python-dateutil=2.4.2=py27_0
- pytz=2015.7=py27_0
- readline=6.2=2
- scipy=0.17.0=np110py27_0
- setuptools=20.1.1=py27_0
- six=1.10.0=py27_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.8=0
- pip:
  - psp (/Users/lev/code/PSP/python)==0.1
  - tables==3.2.2

